/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EExamIdRouteImport } from './routes/e.$examId'
import { Route as ExamsExamIdRouteImport } from './routes/exams.$examId'
import { Route as ExamsExamIdResponsesRouteImport } from './routes/exams_.$examId.responses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EExamIdRoute = EExamIdRouteImport.update({
  id: '/e/$examId',
  path: '/e/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdRoute = ExamsExamIdRouteImport.update({
  id: '/exams/$examId',
  path: '/exams/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdResponsesRoute = ExamsExamIdResponsesRouteImport.update({
  id: '/exams_/$examId/responses',
  path: '/exams/$examId/responses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/e/$examId': typeof EExamIdRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/exams/$examId/responses': typeof ExamsExamIdResponsesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/e/$examId': typeof EExamIdRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/exams/$examId/responses': typeof ExamsExamIdResponsesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/e/$examId': typeof EExamIdRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/exams_/$examId/responses': typeof ExamsExamIdResponsesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/e/$examId' | '/exams/$examId' | '/exams/$examId/responses'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/e/$examId' | '/exams/$examId' | '/exams/$examId/responses'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/e/$examId'
    | '/exams/$examId'
    | '/exams_/$examId/responses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EExamIdRoute: typeof EExamIdRoute
  ExamsExamIdRoute: typeof ExamsExamIdRoute
  ExamsExamIdResponsesRoute: typeof ExamsExamIdResponsesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$examId': {
      id: '/e/$examId'
      path: '/e/$examId'
      fullPath: '/e/$examId'
      preLoaderRoute: typeof EExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId': {
      id: '/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof ExamsExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams_/$examId/responses': {
      id: '/exams_/$examId/responses'
      path: '/exams/$examId/responses'
      fullPath: '/exams/$examId/responses'
      preLoaderRoute: typeof ExamsExamIdResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EExamIdRoute: EExamIdRoute,
  ExamsExamIdRoute: ExamsExamIdRoute,
  ExamsExamIdResponsesRoute: ExamsExamIdResponsesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
